# Generated by Django 2.2.16 on 2021-06-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='style_type',
            field=models.CharField(blank=True, choices=[('Row Layouts', (('rows-divided', 'Dividers Between Articles'),))], help_text='Optional styles for the list itself.', max_length=255, verbose_name='Style Option'),
        ),
    ]
