# Generated by Django 2.2.16 on 2021-06-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccsitearticlelist',
            name='content_type',
        ),
    ]
