# Generated by Django 2.2.16 on 2021-06-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0002_remove_taccsitearticlelist_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='footer_link_text',
            field=models.CharField(blank=True, help_text='The "See All" link at the bottom of the list.', max_length=100),
        ),
    ]
