# Generated by Django 2.2.16 on 2021-06-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0005_auto_20210628_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='layout_type',
            field=models.CharField(choices=[('Row Layouts', (('always-rows-N--even', 'N Equal-Height Rows (always)'),)), ('Column Layouts', (('widest-cols-2--even', '2 Equal-Width Columns (when list is at its widest)'), ('widest-cols-2--wide-narr', '2 Columns: 1 Wide, 1 Narrow (when list is at its widest)'), ('widest-cols-2--narr-wide', '2 Columns: 1 Narrow, 1 Wide (when list is at its widest)'), ('widest-cols-3--even', '3 Equal-Width Columns (when list is at its widest)')))], default='Row Layouts', help_text='Layout of the articles within.', max_length=255, verbose_name='Layout Option'),
        ),
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='style_type',
            field=models.CharField(blank=True, choices=[('Row Layouts', (('rows-divided', 'Dividers Between Articles'),)), ('Any Layouts', (('all-gapless', 'Remove Gaps Between Articles'),))], help_text='Optional styles for the list itself.', max_length=255, verbose_name='Style Option'),
        ),
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='title_text',
            field=models.CharField(blank=True, help_text='The title at the top of the list.', max_length=100, verbose_name='Title Text'),
        ),
    ]
