# Generated by Django 2.2.16 on 2021-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0006_auto_20210628_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='layout_type',
            field=models.CharField(choices=[('Row Layouts', (('rows-always-N-even', 'N Equal-Height Rows (always)'),)), ('Column Layouts', (('cols-widest-2-even', '2 Equal-Width Columns (when list is at its widest)'), ('cols-widest-2-wide-narr', '2 Columns: 1 Wide, 1 Narrow (when list is at its widest)'), ('cols-widest-2-narr-wide', '2 Columns: 1 Narrow, 1 Wide (when list is at its widest)'), ('cols-widest-3-even', '3 Equal-Width Columns (when list is at its widest)')))], default='Row Layouts', help_text='Layout of the articles within.', max_length=255, verbose_name='Layout Option'),
        ),
    ]
