# Generated by Django 2.2.16 on 2021-06-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_list', '0008_auto_20210628_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitearticlelist',
            name='layout_type',
            field=models.CharField(choices=[('Row Layouts', (('rows-always-N-even', 'Multiple Rows'),)), ('Column Layouts', (('cols-widest-2-even', '2 Equal-Width Columns'), ('cols-widest-2-wide-narr', '2 Columns: 1 Wide, 1 Narrow'), ('cols-widest-2-narr-wide', '2 Columns: 1 Narrow, 1 Wide'), ('cols-widest-3-even', '3 Equal-Width Columns')))], default='Row Layouts', help_text='Layout of the articles within. Notice: All Column Layouts become multiple rows when screen width is narrow.', max_length=255, verbose_name='Layout Option'),
        ),
    ]
