# Generated by Django 2.2.16 on 2021-06-16 17:14

from django.db import migrations, models
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_blockquote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccsiteblockquote',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(default=dict),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='quote_alignment',
            field=models.CharField(blank=True, choices=[('text-left', 'Left'), ('text-center', 'Center'), ('text-right', 'Right')], default='text-left', max_length=255),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='quote_origin',
            field=models.CharField(blank=True, help_text='The origin of the quote (i.e. citation, attribution) (e.g. author, source).', max_length=50),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='quote_text',
            field=models.TextField(default=None),
        ),
    ]
