# Generated by Django 2.2.16 on 2021-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_blockquote', '0002_auto_20210616_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsiteblockquote',
            name='quote_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=255),
        ),
    ]
