# Generated by Django 2.2.16 on 2021-06-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_blockquote', '0003_auto_20210616_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccsiteblockquote',
            name='quote_alignment',
        ),
        migrations.RemoveField(
            model_name='taccsiteblockquote',
            name='quote_origin',
        ),
        migrations.RemoveField(
            model_name='taccsiteblockquote',
            name='quote_text',
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='origin',
            field=models.CharField(blank=True, help_text='The origin of the quote (i.e. citation, attribution) (e.g. author, source). This value is ignored if "Advanced origin" fields have data.', max_length=100),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='cite_person',
            field=models.CharField(blank=True, help_text='The author or speaker of the quote.', max_length=50, verbose_name='Author / Speaker'),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='use_cite',
            field=models.BooleanField(default=False, verbose_name='Use the "Citation" fields'),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='cite_url',
            field=models.CharField(blank=True, help_text='URL for the source of the quote.', max_length=255, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='cite_text',
            field=models.CharField(blank=True, help_text='Text for the source of the quote.', max_length=50, verbose_name='Source Text'),
        ),
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='text',
            field=models.TextField(default='', null=True, verbose_name='Quote'),
        ),
    ]
