# Generated by Django 2.2.16 on 2021-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_blockquote', '0004_auto_20210616_1710_squashed_0012_auto_20210616_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='taccsiteblockquote',
            name='offset',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=255),
        ),
    ]
