# Generated by Django 4.2.6 on 2024-01-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropCapOptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttontotoggledropcaps',
            name='title',
        ),
    ]
