# Generated by Django 4.2.6 on 2024-01-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropCapOptions', '0002_remove_buttontotoggledropcaps_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buttonToToggleDropCaps',
            new_name='buttonToToggleDropCap',
        ),
    ]
