version: "3"
services:
  cms:
    extends:
      file: docker-compose.dev.yml
      service: cms
    volumes:
      # Prevents overwrite of auto-built static files by local content
      - /code/static
      - /code/taccsite_cms/static

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  elasticsearch:
    extends:
      file: docker-compose.dev.yml
      service: elasticsearch

volumes:
  core_cms_postgres_data:
  core_cms_es_data:

networks:
  core_cms_net:
