version: "3"
services:
  cms:
    build: .
    image: taccwma/taccsite-cms:initial
    links:
      - postgres:postgres
    volumes:
      - .:/code
    ports:
      - 8001:8001
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8001']
    container_name: texascale_cms
    hostname: texascale_cms
    networks:
      - texascale_cms_net

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=texascale
      - POSTGRES_USER=texascale
      - POSTGRES_DB=texascale
      - PGDATA=/var/lib/postgresql/data/texascale
    volumes:
      - texascale_postgres_data:/var/lib/postgresql/data
      - ./conf/postgres/pg_db.secret:/var/lib/postgresql/pg_db.secret
      - ./conf/postgres/pg_user.secret:/var/lib/postgresql/pg_user.secret
      - ./conf/postgres/pg_password.secret:/var/lib/postgresql/pg_password.secret
    hostname: texascale_postgres
    container_name: texascale_postgres
    networks:
      - texascale_cms_net

volumes:
  texascale_postgres_data:

networks:
  texascale_cms_net:
