# WARNING: The `extends` keyword is NOT supported in Compose version 3.x
# SEE: https://docs.docker.com/compose/extends/#extending-services
version: "3"
services:
  cms:
    extends:
      file: docker-compose.dev.yml
      service: cms
    volumes:
      # Prevent volume sync from host to container for specific directories
      # FAQ: Without this, directories of static files built within docker will be overwritten by empty host directories (because host directories are empty during a fresh setup and all of `/code` is synced as a volume)
      # SEE: https://confluence.tacc.utexas.edu/x/DwAODQ (Solution E)
      - /code/static
      - /code/taccsite_cms/static
      # CMS projects (besides Core) must add a line for their custom resources
      - /code/taccsite_custom/example-cms/static

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  elasticsearch:
    extends:
      file: docker-compose.dev.yml
      service: elasticsearch

volumes:
  core_cms_postgres_data:
  core_cms_es_data:

networks:
  core_cms_net:
