version: "3"
services:
  cms:
    build: .
    image: taccwma/core-cms:latest
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    container_name: core_cms
    hostname: core_cms
    networks:
      - core_cms_net

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=taccforever
      - POSTGRES_USER=postgresadmin
      - POSTGRES_DB=taccsite
      - PGDATA=/var/lib/postgresql/data/taccsite
    volumes:
      - core_cms_postgres_data:/var/lib/postgresql/data
      - ./conf/postgres/pg_db.secret:/var/lib/postgresql/pg_db.secret
      - ./conf/postgres/pg_user.secret:/var/lib/postgresql/pg_user.secret
      - ./conf/postgres/pg_password.secret:/var/lib/postgresql/pg_password.secret
    hostname: core_cms_postgres
    container_name: core_cms_postgres
    networks:
      - core_cms_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ulimits:
      memlock: -1
    environment:
      - ES_HEAP_SIZE:1g
      - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - core_cms_es_data:/usr/share/elasticsearch/data
    container_name: core_cms_elasticsearch
    ports:
      - 9201:9200
    networks:
      - core_cms_net

volumes:
  core_cms_postgres_data:
  core_cms_es_data:

networks:
  core_cms_net:
