version: "3" # https://github.com/compose-spec/compose-spec/blob/3814397/spec.md#version-top-level-element
services:
  cms:
    extends:
      file: docker-compose.example-cms.yml
      service: cms
    volumes:
      # Prevent volume sync from host to container for specific directories
      # FAQ: Prevents overwrite of container directory with empty host directory (which would happen with `static/` and `build/` on a clean setup)
      # SEE: https://confluence.tacc.utexas.edu/x/DwAODQ (Solution E)
      #   The /static` dir is populated by `python … collectstatic` command
      - /code/static
      #   Any `.../build` dirs are populated by `npm … build` command
      #   HACK: No confirmed support for dir globbing, so block all of `static/`
      - /code/taccsite_cms/static

  postgres:
    extends:
      file: docker-compose.example-cms.yml
      service: postgres

  elasticsearch:
    extends:
      file: docker-compose.example-cms.yml
      service: elasticsearch

volumes:
  core_cms_postgres_data:
  core_cms_es_data:

networks:
  core_cms_net:
