# Generated by Django 2.2.16 on 2021-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_greet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitegreet',
            name='guest_name',
            field=models.CharField(blank=True, default='Guest', max_length=50),
        ),
    ]
