# Generated by Django 2.2.16 on 2021-08-16 19:42

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaccsiteSystemMonitor',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='taccsite_system_monitor_taccsitesystemmonitor', serialize=False, to='cms.CMSPlugin')),
                ('system', models.CharField(choices=[('frontera.tacc.utexas.edu', 'Frontera'), ('stampede2.tacc.utexas.edu', 'Stampede2'), ('maverick2.tacc.utexas.edu', 'Maverick2'), ('longhorn.tacc.utexas.edu', 'Longhorn')], default='frontera.tacc.utexas.edu', max_length=255, verbose_name='System')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
