# Generated by Django 2.2.16 on 2021-06-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_offset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccsiteoffset',
            name='alignment',
        ),
        migrations.AddField(
            model_name='taccsiteoffset',
            name='direction',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=255),
        ),
    ]
