# Generated by Django 2.2.16 on 2021-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_data_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitedatalistitem',
            name='key',
            field=models.CharField(blank=True, help_text='A label for the data value.', max_length=50, verbose_name='Label'),
        ),
    ]
