# Merged on top of Core-Styles base config
# SEE: https://github.com/TACC/Core-Styles/blob/main/.postcssrc.base.yml
plugins:
  postcss-import:
    # In any source file, every @import path, not prepended with "./" nor "../",
    # is relative to only one of these directories in this order.
    path:
      - 'taccsite_cms/static/site_cms/css/src' # Core-CMS CSS source files
      - 'node_modules/@tacc/core-styles/src/lib' # Core-Styles CSS source files
  postcss-env-function:
    importFrom:
      - 'node_modules/@tacc/core-styles/src/lib/_themes/default.json'
  postcss-replace:
    pattern: ../../fonts/
    data:
      replaceAll: /static/site_cms/fonts/
