# Merged on top of Core-Styles base config
# SEE: https://github.com/TACC/Core-Styles/blob/main/.postcssrc.base.yml
plugins:
  postcss-import:
    # In any source file, every @import path, not prepended with "./" nor "../",
    # is relative to only one of these directories in this order.
    path:
      - 'taccsite_cms/static/site_cms/css/src' # TACC/Core-CMS
      - 'node_modules/@tacc/core-styles/source' # TACC/Core-Styles
      - 'node_modules/@tacc/core-styles/src/lib' # TACC/tup-ui:/libs/core-styles
  postcss-env-function:
    importFrom:
      - 'node_modules/@tacc/core-styles/src/lib/_themes/default.json'
