# Merged on top of Core-Styles base config
# SEE: https://github.com/TACC/Core-Styles/blob/main/src/.postcssrc.base.yml
plugins:
  postcss-replace:
    # @tacc/core-styles 'src/' uses `("../../fonts/` or `('../../fonts/`
    # @tacc/core-styles 'dist/' uses `(fonts/`
    # Core-CMS 'src/site.…' uses `(fonts/`
    # Core-CMS 'dist/' is not parsed
    pattern: (?<="|'|\()(..\/..\/fonts\/|fonts\/)
    data:
      replaceAll: /static/site_cms/fonts/
