# Merged on top of Core-Styles base config
# SEE: https://github.com/tacc-wbomar/Core-Styles/blob/main/.postcssrc.base.yml
plugins:
  postcss-import:
    path:
      - 'taccsite_cms/static/site_cms/css/src'
      - 'node_modules/@tacc/core-styles/source'
  postcss-env-function:
    importFrom:
      - 'node_modules/@tacc/core-styles/source/_themes/default.json'
