# Generated by Django 2.2.16 on 2021-09-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_callout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitecallout',
            name='description',
            field=models.CharField(help_text='A paragraph for the callout.', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taccsitecallout',
            name='resize_figure_to_fit',
            field=models.BooleanField(default=False, help_text='Make image shorter or taller to match the height of text beside it (as it would be without the image).', verbose_name='Resize any image to fit'),
        ),
        migrations.AlterField(
            model_name='taccsitecallout',
            name='title',
            field=models.CharField(help_text='A heading for the callout.', max_length=100, verbose_name='Title'),
        ),
    ]
