# Generated by Django 2.2.16 on 2021-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('taccsite_callout', '0002_taccsitecallout_resize_figure_to_fit'), ('taccsite_callout', '0003_auto_20210823_1345')]

    dependencies = [
        ('taccsite_callout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taccsitecallout',
            name='resize_figure_to_fit',
            field=models.BooleanField(default=True, help_text='Make image shorter or taller to match the height of text beside it.', verbose_name='Resize any image to fit'),
        ),
    ]
