# Generated by Django 2.2.16 on 2021-08-24 00:02

from django.db import migrations, models
import django.db.models.deletion
import djangocms_link.validators
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0012_file_mime_type'),
        ('taccsite_callout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taccsitecallout',
            name='anchor',
            field=models.CharField(blank=True, help_text='Appends the value only after the internal or external link. Do <em>not</em> include a preceding "#" symbol.', max_length=255, verbose_name='Anchor'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='external_link',
            field=models.CharField(blank=True, help_text='Provide a link to an external source.', max_length=2040, validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='file_link',
            field=filer.fields.file.FilerFileField(blank=True, help_text='If provided links a file from the filer app.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='File link'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='internal_link',
            field=models.ForeignKey(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='mailto',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='target',
            field=models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='taccsitecallout',
            name='template',
            field=models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='taccsitecallout',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='taccsite_callout_taccsitecallout', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
