# Generated by Django 2.2.16 on 2021-06-24 21:03

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('taccsite_static_article_preview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaccsiteStaticAllocsArticlePreview',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='taccsite_static_article_preview_taccsitestaticallocsarticlepreview', serialize=False, to='cms.CMSPlugin')),
                ('media_support', models.CharField(choices=[('nested', 'Nest a single Picture / Image plugin inside this plugin.')], default='nested', max_length=255, verbose_name='How to Add an Image')),
                ('title_text', models.CharField(default='', help_text='The title for the article.', max_length=50, verbose_name='Title')),
                ('abstract_text', models.TextField(default='', help_text='A summary of the article', verbose_name='Abstract')),
                ('publish_date', models.DateField(blank=True, help_text='The date the submissions were opened (manual entry). Format: YYYY-MM-DD', null=True, verbose_name='Date Published')),
                ('expiry_date', models.DateField(blank=True, help_text='The date the submissions were closed (manual entry). Format: YYYY-MM-DD', null=True, verbose_name='Date to Expire')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='taccsitestaticnewsarticlepreview',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date the article was published (manual entry).', null=True, verbose_name='Date Published'),
        ),
    ]
