# Generated by Django 2.2.16 on 2021-06-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccsite_static_article_preview', '0002_auto_20210624_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitestaticallocsarticlepreview',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='The date after which submissions are not accepted (manual entry). Format: YYYY-MM-DD', null=True, verbose_name='Submission End Date'),
        ),
        migrations.AlterField(
            model_name='taccsitestaticallocsarticlepreview',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The date after which submissions are accepted (manual entry). Format: YYYY-MM-DD', null=True, verbose_name='Submission Start Date'),
        ),
    ]
