# Generated by Django 2.2.16 on 2021-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('taccsite_system_specs', '0002_auto_20210929_1238'), ('taccsite_system_specs', '0003_auto_20210929_1247')]

    dependencies = [
        ('taccsite_system_specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitesystemspecs',
            name='system_desc',
            field=models.TextField(default='', help_text='Description of the system machine and mission.', max_length=500, verbose_name='System Description'),
        ),
        migrations.AlterField(
            model_name='taccsitesystemspecs',
            name='other_desc',
            field=models.TextField(blank=True, default='', help_text='Description of "Subsystems and Associated Resources".', max_length=500, verbose_name='Resources Description'),
        ),
    ]
