# Generated by Django 4.2.6 on 2024-02-19 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('taccsite_system_specs', '0002_limit_desc_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccsitesystemspecs',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
