plugins:
  postcss-import:
    path:
      - './taccsite_cms/static/site_cms/css/src'
  postcss-extend: {}
  # Using `importFrom` via `postcss-preset-env` fails (but should work)
  # FAQ: So it is used directly with plugin (not via `postcss-preset-env`)
  # SEE: https://github.com/csstools/postcss-preset-env/issues/202
  # NOTE: Using `postcss-preset-env`'s install of `postcss-env-function` works
  postcss-env-function:
    importFrom:
      - './taccsite_cms/static/site_cms/css/src/_themes/export.js'
  postcss-preset-env:
    # SEE: https://github.com/csstools/postcss-preset-env#features
    stage: false
    features:
      custom-media-queries: true
      media-query-ranges: true
  cssnano:
    preset:
      - 'default'
      -
        # Both of these are disabled to allow manual CSS build tests
        # The `discardDuplicates` is disabled to prevent hiding duplicate CSS
        discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true
