plugins:
  postcss-import:
    path:
      - './taccsite_cms/static/site_cms/css/src'
  postcss-env-function:
    importFrom:
      - './taccsite_cms/static/site_cms/css/src/_themes/export.js'
  postcss-css-variables:
    preserve: 'computed'
    preserveAtRulesOrder: true
  cssnano: {}
