# Generated by Django 4.2.9 on 2025-01-27 20:33

from django.db import migrations


class Migration(migrations.Migration):
    """
    Removes built-in system monitor plugin in favor of external package.

    The new plugin (`djangocms_tacc_system_monitor`) uses:
    - The same CMS plugin type name (`TaccsiteSystemMonitorPlugin`)
    - The same plugin instance data in `cms_cmsplugin`

    NOTE: Due to Django CMS's draft/published page system:
    - Each plugin instance has two copies in the database.
    - One is for draft page. One is for published page. Even if both match.
    - This is normal behavior. This migration handles both copies properly.
    """

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            # To drop the old table
            # CAVEAT:
            # - Plugin instances are lost
            sql="""
            DROP TABLE IF EXISTS taccsite_system_monitor_taccsitesystemmonitor;
            """,

            # To recreate the old table
            # CAVEAT:
            # - Only recreates the empty table structure
            # - Cannot recover any lost data
            reverse_sql="""
            CREATE TABLE taccsite_system_monitor_taccsitesystemmonitor (
                cmsplugin_ptr_id integer NOT NULL PRIMARY KEY REFERENCES cms_cmsplugin(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                system character varying(255) NOT NULL DEFAULT 'frontera.tacc.utexas.edu',
                attributes jsonb NOT NULL DEFAULT '{}'::jsonb
            );
            """
        ),
    ]
